install: lines.h
	mkdir /usr/include/lines
	install lines.h /usr/include/lines
	install util.h /usr/include/lines

update: lines.h
	install lines.h /usr/include/lines
	install util.h /usr/include/lines
